### ISSUE TITLE
Assemblin | Response has value of context from ontotest, not production

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/connector-assemblin#1]
1. Create product using as connector https://api-external.oftrust.net/assemblin/translator/v1/fetch
2. Fetch product as suggested in request body example from Readme, only use the production standard link for @context: https://standards.oftrust.net/v2/Context/DataProductContext/Sensor/

**Result**
Response is returned successfully, with measurements, but the context link returned seems to be hardcoded to ontotest
![image](https://user-images.githubusercontent.com/62647565/109799160-57e19300-7c24-11eb-997d-8fa2073c6615.png)

**Wanted**
Please update so that response contains context link of production: https://standards.oftrust.net/v2/Context/DataProductOutput/Sensor/

**Comment by ralupopa** [comment]
fyi @hoanvancs

**Comment by ralupopa** [comment]
Also for digitransit connector, when fetch getting ontotest context link instead of production

![image](https://user-images.githubusercontent.com/62647565/110128232-3e307f00-7dcf-11eb-96af-349154df4d46.png)

**Comment by j-lex** [comment]
This seems to fixed now.

**Comment by ralupopa** [comment]
@j-lex :
I see that now in response there is : https://standards.oftrust.net/v2/Context/DataProductContext/Sensor/

![image](https://user-images.githubusercontent.com/62647565/118023694-7d96c100-b366-11eb-8d88-9a36e999dfc6.png)


We usually have in response the DataProductOutput link :) Do I understood thus wrongly? (at least on other Fetches this one is returned : https://standards.oftrust.net/v2/Context/DataProductOutput/Sensor/ )

**Comment by j-lex** [comment]
@ralupopa well spotted. We should indeed have the link to the output content in the response. Man I'm glad for your hawk eye.

**Comment by ralucaoanapopa** [comment]
Still reproducing this one:

![image](https://user-images.githubusercontent.com/22395549/157842845-57daf9a1-9238-4e56-a7ad-e592c0562277.png)
